#+TITLE: README FILE FOR PONG
#+AUTHOR: FLURANDO

* PROJECT DESCRIPTION
this little pong implementation in guile using chickadee library

is just a personal learning project to get more comfortable on guile coding

it works more like a template than a game

because to my own experience

the ~chickadee play --repl-server~ and ~chickadee play -repl~ do not work as well as using the mannual way

which is also documented on David Tompson's project page

I have freqently faced the situation of setting some list or data and the game crashed at once

so now I would prefer to use this as a starting point

you are welcomed to use this too

note that though the game.scm file is liscenced as AGPL for fun

you don't need to obey as long as you delete the pong lines

the stuff left over is barely the same with DT's document!

* IMPORTANT NOTES
only the game.scm file is liscenced as I like

the assets now are liscenced separately because that is other people's work

see citation for detail

* INSTALL & SETUP
you need guile chickadee to run this little game

I recommend using guix to have an easy go

just install guix according to the formal website or get one from your package manager and run `guix pull`, followed by some setup according to the hints printed by guix in the terminal

After guix is there, execute ~guix install guile guile-chickadee~ or ~guix shell guile guile-chickadee~

to launch the game, use ~guile game.scm~ or ~./game.scm~ if you gave it right to be executed like a script

* HOW TO PLAY
Use left and right arrow key to move the board at the bottom

Use a and d key to move the board at the top

by the way, when the game window loses the keyboard focus, it would go blank

awesome to be played at CS lessons and work

* HACKING
I would continually change the script and you are welcomed to modify it any how you like, as long as you do it the foss way.

My recommended set up is of course =emacs= + =geiser=!

just start the game and use geiser-connect to connect to it

then just Control-x Control-e or Control-c Control-r to load modified codes or newly written features

* CITATION
1. the bomb music is from a random website which says not royalty music
2. the background music citation
   =Contains music ©2023 Retro Indie Josh (https://retroindiejosh.itch.io) Licensed under Creative Commons Attribution 4.0 International=
3. the ball texture and the background are my own drawing, personally I don't mind reusage as long as there is no commercial use. But I would not liscence them as free now because I am not quite familiar to that.
   Which means, they are simply not liscenced now.
   However, they are actually not drawed technically since I just use Inkscape to assemble some basic shapes
   (well, that's why I am not sure whether I should or could liscence them!)
